import nextConfig from '@galeon/eslint-config/next'
import nodeConfig from '@galeon/eslint-config/node'

/** @type {import('eslint').Linter.Config[]} */
export default [
  // Global ignores
  {
    ignores: [
      '**/node_modules/**',
      '**/dist/**',
      '**/build/**',
      '**/.next/**',
      '**/coverage/**',
      '**/artifacts/**',
      '**/cache/**',
      '**/typechain-types/**',
      '**/ponder-env.d.ts', // Auto-generated by Ponder
    ],
  },

  // Next.js app
  ...nextConfig.map((config) => ({
    ...config,
    files: ['apps/web/**/*.{ts,tsx,js,jsx}'],
  })),

  // Node.js apps and packages
  ...nodeConfig.map((config) => ({
    ...config,
    files: [
      'apps/api/**/*.{ts,js}',
      'apps/indexer/**/*.{ts,js}',
      'packages/stealth/**/*.{ts,js}',
      'packages/contracts/**/*.{ts,js}',
      'packages/eslint-config/**/*.js',
    ],
  })),

  // Allow chai expect() expressions in test files
  {
    files: ['**/test/**/*.ts', '**/*.test.ts'],
    rules: {
      '@typescript-eslint/no-unused-expressions': 'off',
    },
  },

  // Allow empty interface extensions in AdonisJS config files (module augmentation pattern)
  {
    files: ['apps/api/config/**/*.ts'],
    rules: {
      '@typescript-eslint/no-empty-object-type': 'off',
    },
  },
]
